name: Build Kivy APK with Buildozer

on:
  push:
    branches: [ \"main\" ]
  pull_request:
    branches: [ \"main\" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: \"3.9\"

      # تثبيت Java 8 (الأكثر استقراراً مع Android SDK)
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: \"8\"
          distribution: \"adopt\"

      # تثبيت Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3
          ndk-version: 23.2.8568313

      # تثبيت متطلبات النظام
      - name: Install system dependencies
        run: |-
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            ccache \
            autotools-dev \
            autoconf \
            libtool \
            pkg-config

      # إضافة ذاكرة تخزين مؤقتة لـ Buildozer
      - name: Cache Buildozer dependencies
        uses: actions/cache@v3
        with:
          path: |-
            ~/.buildozer
            .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles(\'buildozer.spec\') }}
          restore-keys: |-
            ${{ runner.os }}-buildozer-

      # تثبيت Python packages
      - name: Install Python dependencies
        run: |-
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install \"cython==0.29.33\"
          pip install \"buildozer==1.5.0\"
          pip install \"kivy==2.1.0\"
          pip install colorama appdirs sh jinja2 six arabic_reshaper python-bidi

      # تنظيف وإعداد Buildozer
      - name: Initialize Buildozer
        run: |-
          buildozer android clean
          buildozer android update --verbose

      # بناء APK مع معالجة الأخطاء
      - name: Build APK
        run: |-
          # تعيين متغيرات البيئة
          export ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT
          export ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export PATH=$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools
          
          # بناء APK
          buildozer android debug --verbose
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          ANDROID_NDK_ROOT: ${{ env.ANDROID_NDK_ROOT }}

      # التحقق من وجود APK
      - name: Check APK existence
        run: |-
          echo \"البحث عن ملفات APK...\"
          find . -name \"*.apk\" -type f
          ls -la bin/ || echo \"مجلد bin غير موجود\"

      # رفع APK كـ artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SmartCalculator-APK
          path: |-
            bin/*.apk
            **/*.apk
          retention-days: 30
          if-no-files-found: warn

      # رفع logs في حالة الفشل
      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |-
            .buildozer/
            buildozer.log
            *.log
          retention-days: 7
          if-no-files-found: ignore

      # معلومات التشخيص
      - name: Debug information
        if: always()
        run: |-
          echo \"=== معلومات النظام ===\"
          uname -a
          python --version
          pip list | grep -E \"(kivy|buildozer|cython)\"
          
          echo \"=== متغيرات البيئة ===\"
          echo \"ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT\"
          echo \"ANDROID_NDK_ROOT: $ANDROID_NDK_ROOT\"
          
          echo \"=== محتويات المجلد ===\"
          ls -la
          
          echo \"=== محتويات مجلد .buildozer ===\"
          ls -la .buildozer/ || echo \"مجلد .buildozer غير موجود\"
          
          echo \"=== آخر سطور من buildozer.log ===\"
          tail -50 .buildozer/buildozer.log || echo \"لا يوجد ملف buildozer.log\"
